rm(list=ls())
d <- read.table("SparrowSize.txt", header=TRUE)
d
d1 <- subset(d, d$Wing!='NA')
summary(d1$Wing)
model1 <- lm(Wing~Sex.1 ,data=d1)
summary(model1)
boxplot(d1$Wing~d1$Sex.1, ylab="Wing Length (mm)")
anova(model1)
t.test(d1$Wing~d1$Sex, var.equal=TRUE)
boxplot(d1$Wing~d1$BirdID, ylab="Wing Length (mm)")
require(dplyr)
tbl_df(d1)
glimpse(d1)
d$Mass %>% cor.test(d$Tarsus, na.rm=TRUE)
d1 %>% group_by(BirdID) %>% summarise(count=length(BirdID)) %>% count(count) #count is how many times a bird was measured and n is how many birds were measured count times
model3 <- lm(Wing~as.factor(BirdID), data=d1) #as.factor converts numerical value to factor as each bird was measured 1 or more times
anova(model3)
boxplot(d$Mass~d$Year)
m2 <- lm(d$Mass~as.factor(d$Year))
anova(m2)
summary(m2)
t(model.matrix(m2))
d2 <- subset(d, d$Year!=2000)
model5 <- lm(d2$Mass~as.factor(d2$Year))
anova(model5)
summary(model5)
